# Самостоятельная работа 2

Группа 194

Прикладное программное обеспечение | Рогович Т.В.

27.02.2020

**Списывание и использование телефонов**

Первое предупреждение, сделанное ассистентом или преподавателем: - 1 балл к вашей оценке. 

Второе предупреждение: работа аннулируется без права переписывания.

**Все задачи, где не указано иного, должны принимать значения на ввод (решение для частного случая будет считаться неполным).**

## 1. Тест (2 балла, каждый вопрос по 0,2 балла)

№1. Дан список из слов: ['I', 'love', 'Python']. Необходимо, не используя цикл, получить строку: 'I love python'

In [1]:
spisok = ['I', 'love', 'python']
# ваше решение здесь

№2. Даны 2 списка, при помощи операций над множествами, найдите сумму общих элементов. Функция sum() возвращает сумму.

In [2]:
spisok_1 = [1, 8, 6, 4, 5]
spisok_2 = [4, 3, 1, 5, 6]
# ваше решение здесь

№3. Какой из следующих способов удаления ключа работает со словарями  
a. remove  
b. del  
c. pop  
d. popkey

In [ ]:
# ваше решение здесь

№4. Дана строка 'what a wonderful world'. В цикле for напечатайте на одной строчке каждый третий элемент этой строки, предварительно сделав его заглавной буквой.

Вывод:  
WT NRLOD

In [5]:
stroka = 'what a wonderful world'
# ваше решение здесь
for letter in range(...):
    print(...)

WT NRLOD

№5. Какой из перечисленных типов данных не может быть ключом в словаре:

а. tuple  
b. int  
c. float  
d. list

In [3]:
# ваше решение здесь

№6. Вам дан словарь, содержащий в себе списки словарей. Напишите код, который выведет на экран значение 'SQL' из кортежа ключа 'Язык запросов" в словаре из списка 2.

In [4]:
dict_of_lists = {'Список1': [{'Язык программирования': ('Python', 'R')}, {'Операционная система' : ('Windows', 'UNIX') }], 
                 'Список2' : [{'Язык запросов' : ('SQL', 'DAX')},
                              {'Компания-производитель' : ('IBM', 'Microsoft')}]}
# ваше решение ниже

№7. Есть список из слов, написанных капсом. Необходимо привести все буквы к нижнему регистру, а затем отсортировать список в алфавитном порядке. Цикл использовать нельзя.

In [5]:
spisok = ['BIG', 'QWERTY', 'ALIA', 'DUNE']
# ваше решение здесь

№8. Дан словарь с двумя парами ключ-значение. В каждой паре значение является множеством. Создайте новый ключ в словаре под названием 'Sums', значением которого будет являться суммой пересечения множеств из ключей 'First' и 'Second'. Сумму возвращает функция sum(). Нужно использовать операции над множествами, нельзя просто перенабрать число.

In [6]:
slovar = {'First':{11, 4, 14, 8}, 'Second':{1, 23, 4, 87, 9}}
# ваше решение здесь

№9. Дан список списков. Выведите минимальный элемент каждого подсписка на новой строке. Можно решить эту задачу через цикл, а можно просто сделать три print(). Минимальный элемент возвращается функцией mint()

In [7]:
bolshoy_spisok = [[4, 2, 1], [3, 0.3, 2], [4, -6, 3, 5]]
# ваше решение здесь

№10. На отрезке от 100 и до 499 включительно выведите через запятую на одной строке все числа, кратные 10

Вывод:  
100,110,120...

In [8]:
# ваше решение здесь

## Задача №2. Функции, циклы и map() (1.5 балла)

На вход вам подаются данные через пробел, все из которых являются целыми числами. Вам необходимо вернуть список из этих же чисел после следующих преобразований: если изначальное число было кратным 3 - возвести его в куб и поделить на 2, если не кратным 3 - возвести в квадарт, прибавить единицу и полученную сумму поделить на 3.

*0.5 балла*  
Напишите функцию, которая принимает на ввод число и делает из него куб и делит на 2, если само число было кратным 3, или возводит в квадрат прибавляет единицу и делит сумму на 3, если число было не кратным 3. В обоих случаях результат округляется до целого числа с помощью round().

*0.5 балла*  
Решите задачу применив вашу функцию ко всем элементам списка с помощью цикла for

*0.5 балла*  
Решите задачу применив вашу функцию ко всем элементам списка с функции map()

#### Примеры

**Ввод:**  
1 22 31 4

**Вывод (ваш список, сгенерированный разными способами:)**  
`[1, 162, 321, 6]`

**Ввод:**  
3 2 6

**Вывод (ваш список, сгенерированный разными способами:)**  
`[14, 2, 108]`

In [19]:
# ваше решение здесь

## Задача №3. Факультативы (1 балл)


Группа из 3-х студентов подает заявки в LMS на желаемые факультативы. Каждый студент может выбрать любое количество факультативов из списка математика, английский, физика, право, пение. Факультатив открывается, если его выбрал хотя бы один студент. После того, как студенты осуществляют свой выбор и отправляют заявки, выясняется, что у преподавателей некоторых факультативов не будет возможности вести занятия и эти факультативы отменят. Какие факультативы будут посещать студенты? (Факультатив состоится, если на него подаст заявку хотя бы один студент и его не отменит преподаватель)

**Формат ввода:**

* Заявки на факультативы от студентов: названия факультативов, разделенные пробелом. 
* Для каждого студента факультативы вводятся в новой строке.
* На ввод гарантировано подается информация для трех студентов.
* На четвертой строке вводятся не открывшиеся факультативы

**Формат вывода:**

* Открывшиеся факультативы через запятую на одной строчке (порядок факультативов в выводе может отличаться)

*Пример:*

**Ввод:**  
физика математика   
физика английский право  
право математика  
право физика пение

**Вывод:**  
математика,английский

In [10]:
# ваше решение здесь

## Задача №4. Словари (2 балла)

*1.5 балла*  
Дан словарь с записями, ключами которых являются числа, а значениями словари с регионами и городами (cities).

Также дан словарь, где числам соответствуют географические регионы (regions). Напишите программу, которая сопоставляла бы индекс города из словаря cities с географическим регионом из словаря regions. Программа принимает на вход город, а возращает регион, к которому относится код города.

**Пример ввода**

Москва

**Вывод**
 
Москва - Центральная Россия

*0.5 балла*  
Реализуйте программу, которая на ввод принимает три строки - индекс города (целое число), регион, город.

Программа должна создавать в словаре cities ключ - индекс (тип - целое число), значение которого словарь вида {регион:город}. Для проверки выведите значение только что созданного ключа в словаре cities.

**Пример ввода**  
500   
Томская область  
Томск  

**Вывод**  
(функция для проверки print(cities[500])  
{'Томская область': 'Томск'}

In [11]:
# запустите эту ячейку
cities = {100: {'Московская область': 'Москва'}, 101: {'Ленинградская область':'Санкт-Петербург'}, 103: {'Свердловская область':'Екатеринбург'}, 
          104: {'Пермский край':'Пермь'}, 
          107: {'Красноярский край':'Красноярск'}, 111 : {'Кировская область':'Киров'}, 117 : {'Омская область':'Омск'}}

regions = {'Центральная Россия' : [100], 'Северо-Запад' : [101], 'Поволжье': [104, 111], 'Урал':[103], 'Сибирь': [107, 117]}

In [12]:
# ваше решение здесь

## Задача №5. Магнолия (2 балла)

В магазине "Магнолия" проходит акция - дают скидки на продукты, цена которых делится на сегодняшнее число без остатка. У Маши есть список покупок, состоящий из строк вида "категория@@название@@цена". Помогите ей посчитать количество товаров из ее списка, на которые будет действовать скидка. 

Количество записей в Машином списке покупок может быть любым. Каждая запись вводится с новой строки. Записи вводятся до тех пор, пока пользователь не введет "Конец покупок". 

После этого вводится одно число от 1 до 31 (сегодняшняя дата).

Образец вывода смотрите в примере. Если ни на один товар скидка не действует, то программа должна вывести "Количество товаров со скидкой: 0"

*Если вы правильно считали список покупок и категории - 1 балл.*  
*Подсчет категорий - 1 балл.*

**Пример ввода**

фрукты@@мандарины@@169   
молочные продукты@@молоко@@60  
выпечка@@батон@@26  
алкоголь@@вино@@325   
молочные продукты@@мягкий сыр@@120   
Конец покупок   
13

**Вывод**

Количество товаров со скидкой: 3

In [13]:
# ваше решение здесь

**Задача №6. Шифровальщик (1.5 балла)**

Находясь на экзамене вы с другом придумали способ передвать друг другу информацию, используя зашифрованные сообщения. Напишите функцию, которая принимает на вход исходную строку с информацией, а возвращает его зашифрованный вариант по следующим правилам: 
- Если длина послания меньше 5, то оно копируется дважды (то есть 'cat4' -> 'cat4cat4'
- Если была встречена цифра i, то она меняется на 10-i (например, 8 на 10-8 = 2)
- Все маленькие а меняются на заглавные А.

На ввод вы получаете слово. Вывод - результат работы вашей функции.

*За реализацию каждого условия 0.5 баллов*

*Пример*

**Ввод**  
cat

**Вывод**  
cAtcAt

**Ввод**  
never22

**Вывод**  
never88

In [14]:
# ваше решение здесь